src/WWSC/ThalamusBundle/Entity/Comment.php
<?php

namespace WWSC\ThalamusBundle\Entity;

use WWSC\ThalamusBundle\WWSCThalamusBundle;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Event\LifecycleEventArgs;

/**
 * Comment.
 *
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks
 * @ORM\Table(name="comment", indexes={@ORM\Index(columns={"description"}, flags={"fulltext"})})
 */
class Comment extends Base
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text", nullable=true)
     */
    private $description;

    /**
     * @var string
     *
     * @ORM\Column(name="type", type="string", length=255)
     */
    private $type;

    /**
     * @var boolean
     *
     * @ORM\Column(name="private", type="boolean", nullable=true)
     */
    private $private = 0;

    /**
     * @var integer
     *
     * @ORM\Column(name="parent_id", type="integer")
     */
    private $parent_id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(type="datetime")
     * @Gedmo\Timestampable(on="create")
     */
    private $created;

    private $save_to_log = 1;

    /**
     * @var \DateTime
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated;

    /**
     * @var integer
     *
     * @ORM\ManyToOne(targetEntity="WWSC\ThalamusBundle\Entity\User")
     */
    private $user_created;

    /**
     * @var integer
     *
     * @ORM\ManyToOne(targetEntity="WWSC\ThalamusBundle\Entity\User")
     */
    private $user_updated;

    /**
     * @ORM\Column(name="is_deleted", type="boolean", nullable=true)
     */
    private $is_deleted = 0;

    /**
     * @ORM\OneToOne(targetEntity="WWSC\ThalamusBundle\Entity\TimeTracker", mappedBy="comment", cascade={"all"})
     */
    protected $time_tracker;

    /**
     * Get id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set description.
     *
     * @param string $description
     *
     * @return Task
     */
    public function setDescription($description)
    {
        $this->description = utf8_encode($description);

        return $this;
    }

    /**
     * Get description.
     *
     * @return string
     */
    public function getDescription()
    {
        $description = htmlspecialchars_decode ($this->description);
        if (preg_match('!!u', utf8_decode($description))) {
            return utf8_decode($description);
        } else {
            return $description;
        }
    }

    /**
     * Set created.
     *
     * @param \DateTime $created
     *
     * @return Task
     */
    public function setCreated($created)
    {
        $this->created = $created;

        return $this;
    }

    /**
     * Get created.
     *
     * @return \DateTime
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * Set updated.
     *
     * @param \DateTime $updated
     *
     * @return Task
     */
    public function setUpdated($updated)
    {
        $this->updated = $updated;

        return $this;
    }

    /**
     * Get updated.
     *
     * @return \DateTime
     */
    public function getUpdated()
    {
        return $this->updated;
    }

    /**
     * Set user_created.
     *
     * @ORM\PrePersist()
     *
     * @param \WWSC\ThalamusBundle\Entity\User $userCreated
     *
     * @return Company
     */
    public function setUserCreated($userCreated)
    {
        $this->user_created = WWSCThalamusBundle::getContainer()->get('security.context')->getToken()->getUser();

        return $this;
    }

    /**
     * Get user_created.
     *
     * @return \WWSC\ThalamusBundle\Entity\User
     */
    public function getUserCreated()
    {
        return $this->user_created;
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate
     * Set user_updated
     *
     * @param \WWSC\ThalamusBundle\Entity\User $userUpdated
     *
     * @return Company
     */
    public function setUserUpdated()
    {
        $this->user_updated = WWSCThalamusBundle::getContainer()->get('security.context')->getToken()->getUser();

        return $this;
    }

    /**
     * Get user_updated.
     *
     * @return \WWSC\ThalamusBundle\Entity\User
     */
    public function getUserUpdated()
    {
        return $this->user_updated;
    }

    /**
     * Set is_deleted.
     *
     * @param bool $isDeleted
     *
     * @return Task
     */
    public function setIsDeleted($isDeleted)
    {
        $this->is_deleted = $isDeleted;

        if (1 == $isDeleted) {
            if ($this->getTimeTracker()) {
                foreach ($this->getTimeTracker() as $item) {
                    $item->setIsDeleted(1);
                }
            }
            if ($this->getFiles()) {
                foreach ($this->getFiles() as $item) {
                    $item->removeFile();
                }
            }
        }

        return $this;
    }

    /**
     * Get is_deleted.
     *
     * @return boolean
     */
    public function getIsDeleted()
    {
        return $this->is_deleted;
    }

    /**
     * Set type.
     *
     * @param string $type
     *
     * @return Comment
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Get type.
     *
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Set parent_id.
     *
     * @param int $parentId
     *
     * @return Comment
     */
    public function setParentId($parentId)
    {
        $this->parent_id = $parentId;

        return $this;
    }

    /**
     * Get parent_id.
     *
     * @return integer
     */
    public function getParentId()
    {
        return $this->parent_id;
    }

    public function getParentInfo()
    {
        if ($this->type) {
            $entityManager = WWSCThalamusBundle::getContainer()->get('doctrine')->getManager();
            $critFile = array(
                'is_deleted' => 0,
                'id' => $this->parent_id,
            );

            return $entityManager->getRepository('WWSCThalamusBundle:'.$this->type)->findOneBy($critFile);
        } else {
            return false;
        }
    }

    public function canBeEdited()
    {
        $oUser = WWSCThalamusBundle::getContainer()->get('security.context')->getToken()->getUser();
        if (WWSCThalamusBundle::getContainer()->get('security.context')->isGranted('ROLE_PROVIDER') || $oUser->getId() == $this->getUserCreated()->getId()) {
            $timeCanBeEdited = strtotime('+15 minutes', strtotime($this->created->format('Y-m-d H:i:s'))) - strtotime('now');
            if ($timeCanBeEdited > 0) {
                $timeCanBeEdited = date('i:s', $timeCanBeEdited);

                return $timeCanBeEdited;
            } else {
                return false;
            }
        }

        return false;
    }

    public function getFiles($formatFile = false)
    {
        $entityManager = WWSCThalamusBundle::getContainer()->get('doctrine')->getManager();
        $critFile = array(
            'is_deleted' => 0,
            'parent' => $this->id,
            'type' => 'Comment',
        );
        if ($formatFile) {
            $critFile['format_file'] = $formatFile;
        }

        return $entityManager->getRepository('WWSCThalamusBundle:Files')->findBy($critFile);
    }

    /**
     * Set time_tracker.
     *
     * @param \WWSC\ThalamusBundle\Entity\TimeTracker $timeTracker
     *
     * @return Comment
     */
    public function setTimeTracker(\WWSC\ThalamusBundle\Entity\TimeTracker $timeTracker = null)
    {
        $this->time_tracker = $timeTracker;

        return $this;
    }

    /**
     * Get time_tracker.
     *
     * @return \WWSC\ThalamusBundle\Entity\TimeTracker
     */
    public function getTimeTracker()
    {
        return $this->time_tracker;
    }

    private function getLogInfoByComment($entity)
    {
        if (!$entity->save_to_log) {
            return false;
        }
        $aRes = array();
        $aRes['object_id'] = $entity->getId();
        if ($parent = $entity->getParentInfo()) {
            switch ($entity->getType()) {
                case 'TaskItem':
                    $oTask = $parent->getTask();
                    $oProject = $oTask->getProject();
                    $aRes['project'] = $oProject;
                    $url = '/project/'.$oProject->getSlug().'/task/'.$oTask->getId().'/item/'.$parent->getId().'/comments';
                    if (!$description = $parent->getDescription()) {
                        $description = $parent->gettask()->getName();
                    }
                    $aRes['description'] = "<a href='".$url.'#c_'.$entity->getId()."'>Re:"
                        .$this->truncation($description, 100)
                        .'</a>';
                    break;
                case 'Message' :
                    $oProject = $parent->getProject();
                    $aRes['project'] = $oProject;
                    $url = '/project/'.$oProject->getSlug().'/message/'.$parent->getId().'/comments';
                    $aRes['description'] = "<a href='".$url.'#c_'.$entity->getId()."'>Re:"
                        .$this->truncation($parent->getTitle(), 100)
                        .'</a>';
                    break;
                case 'Writeboard' :
                    $oProject = $parent->getProject();
                    $aRes['project'] = $oProject;
                    $url = '/project/'.$oProject->getSlug().'/Writeboard/'.$parent->getId().'/comments';
                    $aRes['description'] = "<a href='".$url.'#c_'.$entity->getId()."'>Re:"
                        .$this->truncation($parent->getDescription(), 100)
                        .'</a>';

src/WWSC/ThalamusBundle/Form/CommentForm.php
<?php

namespace WWSC\ThalamusBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class CommentForm extends AbstractType {
    /**
     * @param FormBuilderInterface $builder
     * @param array                $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options) {
        $builder
            ->add('description', 'markdown', array('attr' => array('data-provide' => 'markdown', 'rows' => 5)))
            ->add('private', 'checkbox', array('label' => 'Private', 'required' => false, 'label_attr' => array('class' => 'control-label'), 'attr' => array('class' => 'form-control'))) 
        ;
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver) {
        $resolver->setDefaults(array(
            'data_class' => 'WWSC\ThalamusBundle\Entity\Comment',
        ));
    }

    /**
     * @return string
     */
    public function getName() {
        return 'wwsc_thalamusbundle_comment';
    }
}

src/WWSC/ThalamusBundle/Resources/views/Comment/add.html.twig
<div class="avatar-user">
    {% if app.user.avatar %}
        {% set icon = (asset('uploads/user/') ~ app.user.avatar) %}
    {% else %}
        {% set icon = asset('bundles/wwscthalamus/images/user_icon.png') %}
    {% endif %}
    <img src="{{ icon | imagine_filter('my_thumb',{"thumbnail": {"size": [48, 48] }}) }}">
</div>
<form class="form-add-comment" action="{{ path('wwsc_thalamus_project_comment_add', {'project':slugProject,'type':type,'parent':oParent.id})}}" method="Post">
    <div class="error"></div>
    <div class="form-group">
        <p>{% trans %} Leave a comment...{% endtrans %}</p>
        <div class="markdown">
        {% if form.time_tracker is defined and ((is_granted('ROLE_PROVIDER')) or  (is_granted('ROLE_FREELANCER')))%}
            <textarea id="wwsc_thalamusbundle_comment_description" name="wwsc_thalamusbundle_comment[description]"  data-task-id="{{ oParent.id }}" data-provide="markdown" rows="5"></textarea>
        {% else %}
            <textarea id="wwsc_thalamusbundle_comment_description" name="wwsc_thalamusbundle_comment[description]" data-task-id="{{ oParent.id }}"  required="required" data-provide="markdown" rows="5"></textarea>
        {% endif %}
        </div>
    </div>
    {% if (is_granted('ROLE_PROVIDER')) or  (is_granted('ROLE_FREELANCER')) %}
        {% if form.time_tracker is defined %}
            <div class="form-group time-tracker-form">
                <h3> {% trans %} Time tracking to this comment{% endtrans %}</h3>
                {% include 'WWSCThalamusBundle:Comment:time-tracker-form.html.twig' with {'form':form.time_tracker, 'isBillableHours':oParent.task.project.isBillableHours} %}
            </div>
        {% endif %}
    {% endif %}
    {% if type == 'TaskItem'%}
        {% if (is_granted('ROLE_PROVIDER')) %}
            <div class="col-md-12 form-group">
                {{ form_widget(form.private ) }}
                {% trans %} Private: (Visible only to agency companies){% endtrans %}
            </div>
        {% endif %}
        <div class="col-md-12 info-panel">
            <div class="col-md-6">
                Status
                <select id="wwsc_thalamusbundle_task_item_state" name="wwsc_thalamusbundle_task_item[state]" class="form-control">
                    <option value="">{% trans %}  Select please ...{% endtrans %}</option>
                    {% for taskItemStateKey, tasItemState in aTaskItemStates %}
                        <option {% if oParent.state == taskItemStateKey %}selected="selected" {% endif %} value="{{ taskItemStateKey }}">{{ tasItemState }}</option>
                    {%endfor%}
                </select>
            </div>
            <div class="col-md-6">
                {% trans %} Who's responsible?{% endtrans %}
                <select id="wwsc_thalamusbundle_task_item_responsible" name="wwsc_thalamusbundle_task_item[responsible]" class="form-control">
                    <option value="{{ app.user.id }}" >{% trans %}Me{% endtrans %}({{ app.user.firstName }} {{ app.user.lastName }})</option>
                    <option disabled value="">----------</option>
                    {% for oResponsibleCompany in oParent.task.project.subspeople(false,false,true) %}
                        {% if (oResponsibleCompany ['role'] == 'ROLE_PROVIDER') or  (oParent.task.visibleClient == 1 and oResponsibleCompany['role'] == 'ROLE_CLIENT') or (oParent.task.visibleFreelancer == 1 and oResponsibleCompany['role'] == 'ROLE_FREELANCER')%}
                            {% if oResponsibleCompany.people is defined %}
                                {% if oResponsibleCompany['people']|length > 1 or (oResponsibleCompany['people']|length == 1 and app.user.id in oResponsibleCompany['people']|keys == false ) %}
                                    <option disabled value="">{{ oResponsibleCompany['name'] }}</option>
                                    {% for key,val in oResponsibleCompany['people'] %}
                                        {% if app.user.id != key %}
                                            <option {% if key == oParent.responsible.id %} selected {% endif %}  value={{ key }} >{{ val }}</option>
                                        {% endif %}
                                    {%endfor%}
                                    <option disabled value="">----------</option>
                                {% endif %}
                            {% endif %}
                        {% endif %}
                    {%endfor%}
                </select>
            </div>
        </div>
    {% endif %}
    <div class="form-group">
        {% include 'WWSCThalamusBundle:File:attachment-form.html.twig'%}
    </div>
    <input type="hidden" id="wwsc_thalamusbundle_comment__token" name="wwsc_thalamusbundle_comment[_token]" value="{{ form._token.vars.value }}">
    {% if type == 'TaskItem'%}
        {% include 'WWSCThalamusBundle:SubscribeEmail:block-subscribed-people.html.twig'  with {'aSubsCompanies': oParent.task.project.subspeople(false,false,true) , 'activeSubscribed':oParent.activeSubscribed, 'type': 'Task', 'oParent':oParent.task } %}
    {% endif %}
    <div class="form-group  btn-action">
        <button class="btn btn-save btn-primary" type="submit">{% trans %}Add this Comment{% endtrans %}</button>
    </div>
</form>

src/WWSC/ThalamusBundle/Resources/views/Comment/comment-info.html.twig
<div id="c_{{ oComment.id }}" data-id="comment-{{ oComment.id }}" class="comment-item {% if (oComment.description|trim) != true %} empty-comment {% endif %} {{ oComment.private ? 'comment-item-private' : '' }}  info-panel col-md-11">
    <div class="avatar-user">
        {% if oComment.userCreated.avatar %}
            {% set icon = (asset('uploads/user/') ~ oComment.userCreated.avatar) %}
        {% else %}
            {% set icon = asset('bundles/wwscthalamus/images/user_icon.png') %}
        {% endif %}
        <img src="{{ icon | imagine_filter('my_thumb',{"thumbnail": {"size": [48, 48] }}) }}">
    </div>
    <div class="comment-info" >
        <div class="title">
            <span class="user-created" > {{ oComment.userCreated.firstName }}  {{ oComment.userCreated.lastName }}</span>
            <span class="date-created" > {{ oComment.updated|date("D, d M H:i a") }}  </span>
            {% if oComment.canBeEdited %}
                | <a class="btn-edit-comment no-print-this-part"  href="{{ path ('wwsc_thalamus_project_comment_edit',{ 'project':slugProject, 'id': oComment.id}) }}"> {% trans %}Edit{% endtrans %}</a>
                <small class="no-print-this-part"> ({% trans %}for another{% endtrans %}{{ oComment.canBeEdited }} ) </small>
            {% endif %}
            {% if app.session.get('presentationMode') == false  and oComment.timeTracker   and  ( is_granted('ROLE_PROVIDER') or (is_granted('ROLE_FREELANCER') and (oComment.userCreated.company) and (app.user.company.id == oComment.userCreated.company.id)))%}
                <div class="time-tracker-info">
                    {% trans %}reported:{% endtrans %}
                    <span  class="description"> {{ oComment.timeTracker.description}} </span>

                    —
                    <span class="time">{{ oComment.timeTracker.time }} hr</span>
                    {% if oComment.timeTracker.billable != 1 %}
                        <i class="fa fa-strikethrough" aria-hidden="true"></i>
                    {% endif %}
                </div>
            {% endif %}
            {% if is_granted('ROLE_PROVIDER') %}
                <a class="btn-delete-comment no-print-this-part" href="{{ path('wwsc_thalamus_project_comment_delete',{'id': oComment.id}) }}">
                    <i class="fa fa-trash" aria-hidden="true"></i>
                </a>
            {% endif %}
            <a class="btn-link-comment clip_button no-print-this-part" >
                <i class="fa fa-link" aria-hidden="true"></i>
            </a>
            <a onclick =' printDiv("c_{{ oComment.id }}")' class = "btn-link-comment no-print-this-part" >
                <i class="fa fa-print" aria-hidden="true"></i>

            </a>
        </div>
        <div class="description">
            <br>
            {{ oComment.description|escape|markdown }}
            {% if oComment.files %}
                {% include 'WWSCThalamusBundle:File:attachments-list.html.twig' with {'aAttachments': oComment, 'slugProject': slugProject} %}
                <div class="download-all-files-comment">
                    <a href="{{ path ('wwsc_thalamus_project_comment_download_all_files',{ 'project':slugProject, 'id': oComment.id}) }}">
                        {% trans %}Download all files{% endtrans %}
                    </a>
                </div>
            {% endif %}
        </div>
    </div>
</div>

src/WWSC/ThalamusBundle/Resources/views/Comment/edit.html.twig
<script type="text/javascript">
$('.attachment-files').fileupload({
    url: "{{ oneup_uploader_endpoint('files') }}",
    dataType: 'json',
    downloadTemplateId: null,
    type: 'POST'
});
</script>
<form class="form-edit-comment" data-id-comment="comment-{{oComment.id}}" action="{{ path('wwsc_thalamus_project_comment_edit', {'id':oComment.id, 'project' : slugProject} )}}" method="Post">
    <div class="error"></div>
    <div class="form-group">
        <p>{% trans %}Edit this comment…{% endtrans %}</p>
        {{ form_widget(form.description) }}
    </div>
    {% if form.time_tracker is defined %}
        <div class="form-group time-tracker-form">
            <h3> {% trans %}Time tracking to this comment{% endtrans %}</h3>
            {% include 'WWSCThalamusBundle:Comment:time-tracker-form.html.twig' with {'form':form.time_tracker, 'isBillableHours': isBillableHours } %}
        </div>
    {% endif %}
    {% if oComment.type == 'TaskItem'%}
        {% if (is_granted('ROLE_PROVIDER')) %}
            <div class="col-md-12 form-group">
                {{ form_widget(form.private ) }}  
                {% trans %}Private: (Visible only to agency companies){% endtrans %}
            </div>   
        {% endif %}  
        <div class="col-md-12 info-panel">
            <div class="col-md-6">
                {% trans %}Status{% endtrans %}
                <select id="wwsc_thalamusbundle_task_item_state" name="wwsc_thalamusbundle_task_item[state]" class="form-control">
                    <option value="">{% trans %} Select please ...{% endtrans %}</option>
                    {% for taskItemStateKey, tasItemState in aTaskItemStates %}
                        <option {% if oComment.parentInfo.state == taskItemStateKey %}selected="selected" {% endif %} value="{{ taskItemStateKey }}">{{ tasItemState }}</option>
                    {%endfor%}
                </select>
            </div>
            <div class="col-md-6">
                {% trans %}Who's responsible?{% endtrans %}
                <select id="wwsc_thalamusbundle_task_item_responsible" name="wwsc_thalamusbundle_task_item[responsible]" class="form-control">
                    <option value="{{ app.user.id }}">{% trans %}Me{% endtrans %}({{ app.user.firstName }} {{ app.user.lastName }})</option>
                    <option disabled value="">----------</option>
                    {% for oResponsibleCompany in oComment.parentInfo.task.project.subspeople %}
                        {% if (oResponsibleCompany ['role'] == 'ROLE_PROVIDER') or  (oComment.parentInfo.task.visibleClient == 1 and oResponsibleCompany['role'] == 'ROLE_CLIENT') or (oComment.parentInfo.task.visibleFreelancer == 1 and oResponsibleCompany['role'] == 'ROLE_FREELANCER')%}
                            {% if oResponsibleCompany.people is defined %}
                                {% if oResponsibleCompany['people']|length > 1 or (oResponsibleCompany['people']|length == 1 and app.user.id in oResponsibleCompany['people']|keys == false ) %}
                                    <option disabled value="">{{ oResponsibleCompany['name'] }}</option>
                                    {% for key,val in oResponsibleCompany['people'] %}
                                        {% if app.user.id != key %}
                                            <option {% if key == oComment.parentInfo.responsible.id %} selected {% endif %} value={{ key }} >{{ val }}</option>
                                        {% endif %}
                                    {%endfor%}
                                    <option disabled value="">----------</option>
                                {% endif %}
                            {% endif %}
                        {% endif %}
                    {%endfor%}
                </select>
            </div>
        </div>
    {% endif %}
    <div class="form-group">
        {% include 'WWSCThalamusBundle:File:attachment-form.html.twig'  with {'aFiles': oComment.files, 'project' : slugProject} %} 
    </div>
    {{ form_widget(form._token) }}
    {% if oComment.type == 'TaskItem'%}
        {% include 'WWSCThalamusBundle:SubscribeEmail:block-subscribed-people.html.twig'  with {'aSubsCompanies': oComment.parentInfo.task.project.subspeople , 'activeSubscribed':oComment.parentInfo.activeSubscribed, 'type': 'Task', 'oParent':oComment.parentInfo.task} %} 
    {% endif %}
    <div class="form-group  btn-action"> 
        <button class="btn btn-save btn-primary" type="submit">{% trans %}Update this Comment{% endtrans %}</button>
    </div>    
</form>

src/WWSC/ThalamusBundle/Resources/views/Comment/list.html.twig
<div class="col-md-12">  
    <div class="comments-list col-md-12">
        {% for oComment in aComment  %}
            {% include 'WWSCThalamusBundle:Comment:comment-info.html.twig' with {'project':slugProject, 'oComment': oComment} %}               
        {% endfor  %}
    </div>
    <iframe name="print_frame" width="0" height="0" frameborder="0" src="about:blank"></iframe>
    <div class="col-md-12"> 
        <div class="form-comment col-md-11">  
            {{ render(controller('WWSCThalamusBundle:Comment:add',{'project':slugProject,'type':type,'parent':parent} )) }}
        </div>
    </div>
</div>  

src/WWSC/ThalamusBundle/Resources/views/Comment/time-tracker-form.html.twig
<div class="col-md-12 info-panel">
    <div class=" from-group col-md-12">
        <span class="col-md-2">{% trans %}Description:{% endtrans %}</span>
        <div class="col-md-10"><input type="text" id="wwsc_thalamusbundle_comment_time_tracker_description" name="wwsc_thalamusbundle_comment[time_tracker][description]" required="required" class="form-control" value="{{ form.description.vars.value }}" maxlength="2000"></div>
    </div>
    <div class=" from-group col-md-12">
        <div class="col-md-8 without-padding">
            <span class="col-md-3">{% trans %}Time:{% endtrans %}</span>
            <div class="col-md-4"><input type="text" id="wwsc_thalamusbundle_comment_time_tracker_time" name="wwsc_thalamusbundle_comment[time_tracker][time]" required="required" class="form-control" value="{{ form.time.vars.value }}" pattern="^([0-9])*([.]([0-9]){1,2}|[:](([0-5][0-9])|([6-9])))?$"></div>
            <span class="col-md-4"><small>(eg 2.5, or 2:30)</small></span>
        </div>
        <div class="col-md-4 without-padding">
            <span >{% trans %}Billable{% endtrans %}</span>
            <input type="checkbox" {% if isBillableHours  %} checked="checked"  {% endif %} id="wwsc_thalamusbundle_comment_time_tracker_billable" name="wwsc_thalamusbundle_comment[time_tracker][billable]">
        </div>
        <div class="timespan-since-last-time col-md-12">
            {% if app.user.timespanSinceLastTime() %}
                <a href = "#">
                    {% trans %} Timespan since last time tracking: {% endtrans %} <span>{{  app.user.timespanSinceLastTime() }}</span>
                </a>
            {% endif %}
        </div>
    </div>
</div>