src/WWSC/ThalamusBundle/Entity/User.php
<?php

namespace WWSC\ThalamusBundle\Entity;

use FOS\UserBundle\Model\User as BaseUser;
use WWSC\ThalamusBundle\WWSCThalamusBundle;
use WWSC\ThalamusBundle\Entity\UserProfile as Profile;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity
 * @Vich\Uploadable
 * @ORM\HasLifecycleCallbacks
 * @ORM\Table(name="fos_user")
 */
class User extends BaseUser
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @Assert\File(
     *     maxSize="5M",
     *     mimeTypes={"image/png", "image/jpeg", "image/pjpeg"}
     * )
     * @Vich\UploadableField(mapping="user_avatar", fileNameProperty="avatar")
     *
     * @var File
     */
    protected $avatarFile;

    /**
     * @var string
     *
     * @ORM\Column(name="avatar", type="string", length=255, nullable=true)
     */
    private $avatar;

    /**
     * @var string
     *
     * @ORM\Column(name="first_name", type="string", length=100)
     * @Assert\NotBlank(message="Please enter your first Name.")
     * @Assert\Length(
     *     min=2,
     *     max="255",
     *     minMessage="The First Name is too short.",
     *     maxMessage="The First Name is too long.",
     * )
     */
    private $firstName;

    /**
     * @var string
     *
     * @ORM\Column(name="last_name", type="string", length=100)
     * @Assert\NotBlank(message="Please enter your last Name.")
     * @Assert\Length(
     *     min=2,
     *     max="255",
     *     minMessage="The Last Name is too short.",
     *     maxMessage="The Last Name is too long.",
     * )
     */
    private $lastName;

    /**
     * @var string
     *
     * @ORM\Column(name="language", type="string", length=100, nullable=true)
     */
    private $language;

    /**
     * @var string
     *
     * @ORM\Column(name="time_zone", type="string", length=100, nullable=true)
     */
    private $timeZone;

    /**
     * @var bool
     *
     * @ORM\Column(name="access_all_projects", type="boolean", nullable=true)
     */
    private $accessAllProjects;

    /**
     * @ORM\OneToOne(targetEntity="WWSC\ThalamusBundle\Entity\UserProfile", mappedBy="user", cascade={"all"})
     */
    protected $profile;

    /**
     * @var \DateTime
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated;

    /**
     * @ORM\OneToMany(targetEntity="WWSC\ThalamusBundle\Entity\CompanyUser", mappedBy="user")
     */
    private $companyUser;

    /**
     * @ORM\ManyToMany(targetEntity="WWSC\ThalamusBundle\Entity\Project", mappedBy="users")
     */
    private $project;

    /**
     * @ORM\Column(name="sorting_projects_list", type="integer", nullable=true)
     */
    public $sorting_projects_list;

    /**
     * @ORM\Column(name="last_logged_account", type="integer", nullable=true)
     */
    public $last_logged_account;

    /** @ORM\Column(name="googleID", type="string", length=255, nullable=true) */
    protected $googleID;

    /** @ORM\Column(name="google_access_token", type="string", length=255, nullable=true) */
    protected $google_access_token;

    /**
     * @ORM\Column(name="is_deleted", type="boolean", nullable=true)
     */
    private $is_deleted = 0;

    /**
     * @ORM\Column(name="locked", type="integer")
     */
    protected $locked = 0;

    /**
     * @ORM\Column(name="google_drive_token", type="string", length=255, nullable=true)
     */
    protected $google_drive_token;

    /**
     * @ORM\Column(name="google_drive_token_expire", type="string", length=255, nullable=true)
     */
    protected $google_drive_token_expire;

    /**
     * @ORM\Column(name="google_drive_token_refresh", type="string", length=255, nullable=true)
     */
    protected $google_drive_token_refresh;

    public $account;

    /**
     * Constructor.
     */
    public function __construct()
    {
        parent::__construct();
        $this->project = new \Doctrine\Common\Collections\ArrayCollection();
        $this->companyUser = new \Doctrine\Common\Collections\ArrayCollection();
    }

    public function setProfile(Profile $profile)
    {
        $this->profile = $profile;
    }

    public function getProfile()
    {
        return $this->profile;
    }

    /**
     * @ORM\PrePersist()
     */
    public function prePersist() {
        if(!$this->salt){
            $this->salt = base_convert(sha1(uniqid(mt_rand(), true)), 16, 36);
        }
    }

    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param UploadedFile $avatarFile
     */
    public function setAvatarFile(File $avatarFile)
    {
        $this->avatarFile = $avatarFile;
        $this->updated = new \DateTime();
    }

    /**
     * @return File
     */
    public function getAvatarFile()
    {
        return $this->avatarFile;
    }

    public function getLanguageCode()
    {
        if ('de' == $this->language || 'de_AT' == $this->language) {
            return 'de';
        } else {
            return 'en';
        }
    }

    /**
     * Set avatar.
     *
     * @param string $avatar
     *
     * @return User
     */
    public function setAvatar($avatar)
    {
        $this->avatar = $avatar;
    }

    /**
     * Get avatar.
     *
     * @return string
     */
    public function getAvatar()
    {
        return $this->avatar;
    }

    public function getCompany($account = false)
    {
        if (!$account) {
            $account = WWSCThalamusBundle::getContainer()->get('session')->get('account')->id;
        }
        $qb = WWSCThalamusBundle::getContainer()->get('doctrine')->getManager()->createQueryBuilder();
        $qb->select('c')
            ->from('WWSC\ThalamusBundle\Entity\Company', 'c')
            ->join('WWSC\ThalamusBundle\Entity\CompanyUser', 'cu', 'WITH', '(c.id = cu.company)')
            ->where('cu.user = '.$this->getId())
            ->andWhere('c.account = '.$account)
            ->setMaxResults(1);

        return $qb->getQuery()->getOneOrNullResult();
    }

    public function getRole()
    {
        $qb = WWSCThalamusBundle::getContainer()->get('doctrine')->getManager()->createQueryBuilder();
        $qb->select('ru.key')
            ->from('WWSC\ThalamusBundle\Entity\RoleUser', 'ru')
            ->join('WWSC\ThalamusBundle\Entity\CompanyUser', 'cu', 'WITH', '(ru.id = cu.role_user)')
            ->where('cu.user = '.$this->getId())
            ->andWhere('cu.company = '.$this->getCompany()->getId())
            ->setMaxResults(1);
        if ($oRole = $qb->getQuery()->getOneOrNullResult()) {
            return $oRole['key'];
        } else {
            return false;
        }
    }

    public function setCompany($oCompany)
    {
        if ($oCompany->getId() != $this->getCompany()->getId()) {
            $enabled = $this->checkActiveUserCompany();
            $this->removeCompanyUser($this->getCompany());
            $this->addCompanyUser($oCompany, $enabled);
        }
    }

    public function getAccount()
    {
        return $this->account;
    }

    /**
     * Set firstName.
     *
     * @param string $firstName
     *
     * @return User
     */
    public function setFirstName($firstName)
    {
        $this->firstName = $firstName;

        return $this;
    }

    /**
     * Get firstName.
     *
     * @return string
     */
    public function getFirstName()
    {
        return $this->firstName;
    }

    public function getLastName()
    {
        return $this->lastName;
    }

    /**
     * Set lastName.
     *
     * @param string $lastName
     *
     * @return User
     */
    public function setLastName($lastName)
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * Set language.
     *
     * @param string $language
     *
     * @return User
     */
    public function setLanguage($language)
    {
        $this->language = $language;

        return $this;
    }

    /**
     * Get language.
     *
     * @return string
     */
    public function getLanguage()
    {
        return $this->language;
    }

    /**
     * Set timeZone.
     *
     * @param string $timeZone
     *
     * @return User
     */
    public function setTimeZone($timeZone)
    {
        $this->timeZone = $timeZone;

        return $this;
    }

    /**
     * Get timeZone.
     *
     * @return string
     */
    public function getTimeZone()
    {
        return $this->timeZone;
    }

    /**
     * Set accessAllProjects.
     *
     * @param bool $accessAllProjects
     *
     * @return User
     */
    public function setAccessAllProjects($accessAllProjects)
    {
        $this->accessAllProjects = $accessAllProjects;

        return $this;
    }

    /**
     * Get accessAllProjects.
     *
     * @return bool
     */
    public function getAccessAllProjects()
    {
        return $this->accessAllProjects;
    }

    /**
     * Set updated.
     *
     * @param \DateTime $updated
     *
     * @return User
     */
    public function setUpdated($updated)
    {
        $this->updated = $updated;

        return $this;
    }

    /**
     * Get updated.
     *
     * @return \DateTime
     */
    public function getUpdated()
    {
        return $this->updated;
    }

    /**
     * Add project.
     *
     * @param \WWSC\ThalamusBundle\Entity\Project $project
     *
     * @return User
     */
    public function addProject(\WWSC\ThalamusBundle\Entity\Project $project)
    {
        $this->project[] = $project;

        return $this;
    }

    /**
     * Remove project.
     *
     * @param \WWSC\ThalamusBundle\Entity\Project $project
     */
    public function removeProject(\WWSC\ThalamusBundle\Entity\Project $project)
    {
        $this->project->removeElement($project);
    }

    /**
     * Get project.
     *

src/WWSC/ThalamusBundle/Form/UserForm.php
<?php

namespace WWSC\ThalamusBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Symfony\Component\HttpFoundation\File\File;

class UserForm extends AbstractType {
    /**
     * @param FormBuilderInterface $builder
     * @param array                $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options) {
        $builder
                ->add('email', 'email', array('label' => 'form.email', 'label_attr' => array('class' => 'control-label'), 'label_attr' => array('class' => 'control-label col-md-2'), 'attr' => array('class' => 'form-control'), 'translation_domain' => 'FOSUserBundle'))
                ->add('first_name', 'text', array('label' => 'First name', 'label_attr' => array('class' => 'control-label col-md-2'), 'attr' => array('class' => 'form-control', 'pattern' => '.{3,100}')))
                ->add('last_name', 'text', array('label' => 'Last name', 'label_attr' => array('class' => 'control-label col-md-2'), 'attr' => array('class' => 'form-control', 'pattern' => '.{3,100}')))
                ->add('plainPassword', 'repeated', array(
                    'type' => 'password',
                    'label_attr' => array('class' => 'control-label'),
                    'required' => false,
                    'options' => array('translation_domain' => 'FOSUserBundle'),
                    'first_options' => array('label' => false, 'attr' => array('class' => 'form-control', 'pattern' => '(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{6,}', 'placeholder' => 'Password')),
                    'second_options' => array('label' => false, 'attr' => array('class' => 'form-control', 'pattern' => '(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{6,}', 'placeholder' => 'Confirm password')),
                    'invalid_message' => 'fos_user.password.mismatch',
                ))
                ->add('avatarFile', 'file', array('label' => 'Upload your photo', 'required' => false, 'label_attr' => array('class' => 'control-label'), 'attr' => array('class' => 'form-control')))
                ->add('language', 'language', array('label' => 'Language', 'required' => false, 'label_attr' => array('class' => 'control-label col-md-2'), 'attr' => array('class' => 'form-control')))
                ->add('timeZone', 'readabletimezone', array('label' => 'Time Zone', 'required' => false, 'label_attr' => array('class' => 'control-label col-md-2'), 'data' => 'Europe/Amsterdam', 'attr' => array('class' => 'form-control time-zone')));
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver) {
        $resolver->setDefaults(array(
            'data_class' => 'WWSC\ThalamusBundle\Entity\User',
        ));
    }

    /**
     * @return string
     */
    public function getName() {
        return 'wwsc_thalamusbundle_user';
    }
}

src/WWSC/ThalamusBundle/Resources/views/User/activation_user.html.twig
{% extends '::base.html.twig' %}
{% block title %}
    {% trans %}Activation user{% endtrans %}
{% endblock %} 
{% block body %}
<div class="container activation_user modal-content">
    {% if form is defined %}
        <form action="{{ path('wwsc_thalamus_user_activation',{'account': oAccount.slug, 'token':token}) }}" method="post" class="form-signin">
            <h2>{{ oAccount.name }}</h2>
            {% include 'WWSCThalamusBundle:Content:flash_notice.html.twig' %}
            <p>{% trans %}Please set your personal password first{% endtrans %}</p>
            <div class="form-group plain-password">
                {% set msgValidPassword = oUser.languageCode =='de' ? 'Passwort nicht korrekt. Mind. 6 Zeichen, inkl. 1 Grossbuchstabe und eine Ziffer erforderlich.': 'Password incorrect. 6 characters necessary including 1 uppercase and 1 numeric.' %}
                {{ form_widget(form.plainPassword.first, {'attr': {'title':'"'~ msgValidPassword ~'"'} } ) }}
                {{ form_widget(form.plainPassword.second, {'attr': {'title':'"'~ msgValidPassword ~'"'} } ) }}
            </div>
            {{ form_widget(form._token) }}
            <div class="form-group">
                {{ form_widget(form._token) }}
                <button class="btn btn-lg btn-primary btn-block"  type="submit">{% trans %}OK, let's go{% endtrans %}</button>
            </div>
        </form>
    {% else %}
        {% include 'WWSCThalamusBundle:Content:flash_notice.html.twig' %}
    {% endif %}    
</div>
{% endblock %}

src/WWSC/ThalamusBundle/Resources/views/User/add.html.twig
{% extends "WWSCThalamusBundle:Content:layout.html.twig" %}
{% block title %}
    {% trans %}Add new person{% endtrans %}
{% endblock %} 
{% block content %}   
    <div class="row">
        <div class="panel panel-default col-md-9">
            <div class="panel-heading">
                {% trans %}Add a person to{% endtrans %} {{oCompany.name}}
            </div>
            <div class="panel-body">
                <div class="row">
                    {% include 'WWSCThalamusBundle:Content:flash_notice.html.twig' %}
                    {% if form_errors(form) %}
                        <div class="alert alert-error error" role="alert">{{ form_errors(form) }}</div>
                    {% endif %}
                    <div class="panel-forms">
                        <form action="{{ path('wwsc_thalamus_user_add', {'company': oCompany.id}) }}" class="add-user-form" method="Post">
                            <input type='hidden' name="company" id="company_id" value="{{ oCompany.id }}">
                            {% if app.request.get('project') %}
                                <input type='hidden' id="wwsc_thalamus_user_project"  name="project" value="{{ app.request.get('project')}}">
                            {% endif %}
                            <p>{% trans %}This person's name will be displayed next to their messages, comments, to-dos, milestones, and files.{% endtrans %}</p>
                            <fieldset>
                                <div class="form-group col-xs-12">
                                    {{form_label(form.first_name )}}
                                    <div class="col-md-4">  
                                        {{form_widget(form.first_name )}}
                                    </div>
                                </div>
                                <div class="form-group col-xs-12">
                                    {{form_label(form.last_name )}}
                                    <div class="col-md-4">      
                                        {{form_widget(form.last_name )}}
                                    </div>
                                </div>
                                <div class="form-group col-xs-12">
                                    {{form_label(form.email )}}
                                    <div class="col-md-4">       
                                        {{form_widget(form.email )}}
                                    </div>
                                </div>
                            {% if is_granted('ROLE_PROVIDER') %}
                                <div class="form-group col-xs-12">
                                    {{form_label(form.language )}}
                                    <div class="col-md-4">       
                                        {{form_widget(form.language )}}
                                    </div>
                                </div>
                            {% endif %}
                            {% if aRoles is defined %}
                                <div class="form-group col-xs-12">
                                    <label class="control-label col-md-2" for="wwsc_thalamusbundle_user_language">Role User</label>
                                    <div class="col-md-4">       
                                        <select name="role-user" class="form-control">
                                            <option></option>
                                             {% for oRole in aRoles %}
                                                 <option value="{{ oRole.key }}">{{ oRole.name }}</option>
                                            {% endfor %}
                                        </select>    
                                    </div>
                                </div>
                            {% endif %} 
                            </fieldset>    
                            <p>{% trans %}The rest is optional. You can fill it in later if you'd like.{% endtrans %}</p>
                            <fieldset>
                                {% include 'WWSCThalamusBundle:User:profile_form.html.twig' with {'profile': form.profile} %}
                            </fieldset>  
                            <h3>{% trans %}Include a personal note along with the invitation to set up their account?{% endtrans %}</h3>
                            <p>{% trans %}This person will receive a welcome email with a link to choose their username and password. You can also add a personalized note that will appear at the bottom of the email. Please use plain text (no HTML tags).{% endtrans %}</p>
                            <fieldset>
                                <div class="form-group col-xs-12">
                                    <div class="col-md-6"> 
                                        {{form_widget(form.profile.description )}}
                                    </div>
                                </div>
                            </fieldset>     
                            {{ form_widget(form._token) }}
                            <h3>{% trans %}What happens now?{% endtrans %}</h3>
                            <p>{% trans %}When you click the "Add this person" button below, we'll fire off a nice invitation to the email address you entered above. The email will contain a link to a web page where this person will complete the setup process by picking their own username and password. Plus, you can immediately start involving them in projects even before they've chosen their username and password.{% endtrans %}</p>
                            <div class="form-group col-xs-12 btn-action">
                                <button class="btn btn-sm btn-primary btn-save" type="submit">{% trans %}Save changes{% endtrans %}</button>
                                or <a class="btn-cancel" href="{{ path ('wwsc_thalamus_account_all_people') }}">{% trans %}Cancel{% endtrans %} </a> 
                            </div>
                        </form>
                    </div>
                </div>
            </div>  
        </div>                          
        <div class="col-md-3 sidebar sidebar-user">
            <div class="col">
                <div class="title-panel">{% trans %}Sample welcome email{% endtrans %}</div>
                <div class="info-panel">
                    {% trans %}As soon as you submit this form, this person will receive a welcome email with a link to pick their own username and password.{% endtrans %}
                </div>   
            </div>
        </div><!--/span-->
    </div>
{% endblock %}       

src/WWSC/ThalamusBundle/Resources/views/User/block_info_user.html.twig
<div class="name">
    {{ user.firstName }} {{ user.lastName }}
</div><br>
<ul>
    <li>{{ user.firstName }}</li>
    <li>{{ user.email }}</li>
        {% if user.profile.imName %}
        <li>{{ user.profile.serviceIm }} : {{ user.profile.imName }}</li>
        {% endif %}
        {% if user.profile.office %}
        <li>O: {{ user.profile.office }}</li>
        {% endif %}
        {% if user.profile.mobile %}
        <li>M: {{ user.profile.mobile }}</li>
        {% endif %}
        {% if user.profile.fax %}
        <li>H: {{ user.profile.fax }}</li>
        {% endif %}
        {% if user.profile.home %}
        <li>F: {{ user.profile.home }}</li>
        {% endif %}
</ul>

src/WWSC/ThalamusBundle/Resources/views/User/my_info.html.twig
{% extends "WWSCThalamusBundle:Content:layout.html.twig" %}
{% block title %}
    {% trans %}My info{% endtrans %}
{% endblock %} 
{% block content %}
    <div class="row col-xs-offset-2 col-md-7">
    <div class="panel panel-default">
        <div class="panel-heading">
            {% trans %}Update your Thalamus ID details{% endtrans %}
        </div>
        <div class="panel-body">
            <div class="row">
                {% include 'WWSCThalamusBundle:Content:flash_notice.html.twig' %}
                {% if form_errors(form) %}
                    <div class="alert alert-error error" role="alert">{{ form_errors(form) }}</div>
                {% endif %}
                <div class="panel-forms">
                    <form class="my-info" action="{{ path('wwsc_thalamus_user_myinfo' ) }}" {{ form_enctype(form) }}
                          method="Post">
                        <div class="form-group col-md-12">
                            <div class="avatar-user col-md-2">
                                {% if app.user.avatar %}
                                    {% set icon = (asset('uploads/user/')~ app.user.avatar) %}
                                {% else %}
                                    {% set icon = asset('bundles/wwscthalamus/images/user_icon.png') %}
                                {% endif %}
                                <img src="{{ icon | imagine_filter('my_thumb',{"thumbnail": {"size": [64, 64] }}) }}">
                            </div>
                            <div class="col-md-7">
                                {{ form_label(form.avatarFile) }}
                                {{ form_widget(form.avatarFile) }}
                            </div>
                        </div>
                        <div class="form-group col-xs-12">
                            {{ form_label(form.first_name ) }}
                            <div class="col-md-7">
                                {{ form_widget(form.first_name ) }}
                            </div>
                        </div>
                        <div class="form-group col-xs-12">
                            {{ form_label(form.last_name ) }}
                            <div class="col-md-7">
                                {{ form_widget(form.last_name ) }}
                            </div>
                        </div>
                        <div class="form-group col-xs-12">
                            {{ form_label(form.email ) }}
                            <div class="col-md-7">
                                {{ form_widget(form.email ) }}
                            </div>
                        </div>
                        {% if aRoles is defined %}
                            <div class="form-group col-xs-12">
                                <label class="control-label col-md-2" for="wwsc_thalamusbundle_user_language">Role
                                    User</label>
                                <div class="col-md-4">
                                    <select name="role-user" class="form-control">
                                        <option></option>
                                        {% for oRole in aRoles %}
                                            <option {% if app.user.role == oRole.key %} selected {% endif %}
                                                    value="{{ oRole.key }}">{{ oRole.name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                        {% endif %}
                        <div class="form-group  col-xs-12">
                            {{ form_label(form.language) }}
                            <div class="col-md-7">
                                {{ form_widget(form.language) }}
                            </div>
                        </div>
                        <div class="form-group col-xs-12">
                            <label class="control-label col-md-2" for="wwsc_thalamusbundle_user_language">
                                {% trans %}Project for Screenshot Tool{% endtrans %}
                            </label>
                            <div class="col-md-7">
                                {% include 'WWSCThalamusBundle:Project:project-for-screenshot-tool.html.twig' with {'oUser': app.user} %}
                            </div>
                        </div>
                        <div class="form-group  col-xs-12">
                            {{ form_label(form.timeZone) }}
                            <div class="col-md-7">
                                {{ form_widget(form.timeZone) }}
                            </div>
                        </div>
                        <div class="form-group col-xs-12 plain-password">
                            <label class="control-label col-xs-2 "
                                   for="wwsc_thalamusbundle_user_plainPassword">{% trans %}
                                Password:{% endtrans %}</label>
                            <div class="col-md-7">
                                {% set msgValidPassword = app.user.languageCode =='de' ? 'Passwort nicht korrekt. Mind. 6 Zeichen, inkl. 1 Grossbuchstabe und eine Ziffer erforderlich.': 'Password incorrect. 6 characters necessary including 1 uppercase and 1 numeric.' %}
                                {{ form_widget(form.plainPassword.first, {'attr': {'title':'"'~ msgValidPassword ~'"'} } ) }}
                                {{ form_widget(form.plainPassword.second, {'attr': {'title':'"'~ msgValidPassword ~'"'} } ) }}
                            </div>
                        </div>
                        <div class="form-group col-xs-12">
                            <label class="control-label col-md-2"></label>
                            <div class="col-md-7">
                                <b>{% trans %}Sync with services:{% endtrans %}</b>
                            </div>
                        </div>
                        {{ form_widget(form._token) }}
                        <div class="form-group col-xs-12 btn-action">
                            <label class="control-label col-md-2"></label>
                            <div class="col-md-7">
                                <button class="btn btn-sm btn-primary btn-save" type="submit">{% trans %}Save
                                    changes{% endtrans %}</button>
                                or <a class="btn-cancel" href="{{ path ('wwsc_thalamus_account_all_people') }}"> {% trans %}
                                    Cancel{% endtrans %} </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    <script src="https://apis.google.com/js/platform.js?onload=init" async defer></script>
{% endblock %}
{% block oauth %}
    <meta name="google-signin-client_id" content="937626635370-n4hom44245qcqo9flf2sflu34tboppqb.apps.googleusercontent.com">
{% endblock %}

src/WWSC/ThalamusBundle/Resources/views/User/my_info_block.html.twig
<div class=" panel panel-default col-md-4 my-info-block">
    <div class="panel-heading col-xs-12">
        {% trans %}Your Tgalamus Id{% endtrans %}
    </div>
    <div class="panel-body">
        <div class="item col-xs-12">
            <div class="avatar">
                {% if oUser.avatar %}
                    {% set icon = (asset('uploads/user/') ~ oUser.avatar) %}
                {% else %}
                    {% set icon = asset('bundles/wwscthalamus/images/user_icon.png') %}
                {% endif %}
                <img src="{{ icon | imagine_filter('my_thumb',{"thumbnail": {"size": [64, 64] }}) }}">
            </div>
            <div class="desc">
                <div class="name">
                    {{ oUser.firstName }} {{ oUser.lastName }}
                </div>
                <ul>
                    <li>{{ oUser.email }}</li>
                    <li>{% trans %}Username:{% endtrans %} {{ oUser.username }}</li>
                    <li>{% trans %}Password:{% endtrans %} •••••• </li>
                </ul>                               
            </div>
        </div>
    </div>
</div>

src/WWSC/ThalamusBundle/Resources/views/User/popup_add_existing_user.html.twig
<div class="modal add-existing-user container">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">{{ oUser['firstName']}} {{oUser['lastName']}} {% trans %}already exists on Thalamus account{% endtrans %}</h4>
      </div>
      <div class="modal-body">
        <p>{{ oUser['firstName']}} {{oUser['lastName']}}'s {% trans %}email address{% endtrans %} ({{oExistentUser['email']}}) {% trans %}already matches someone else on Thalamus account named{% endtrans %} {{oExistentUser['firstName']}} {{oExistentUser['lastName']}}.</p>
        <p>{% trans %}Are you sure you want to add this user to your account?{% endtrans %}</p>
        <p><div class="form-group without-padding  btn-action">
            <a class="btn btn-sm btn-primary btn-save" href="{{ path('wwsc_thalamus_add-existent-user-to-company',{'company': oUser['company'], 'user': oExistentUser.id, 'project': oUser['project']})}}">{% trans %}Add user to account{% endtrans %}</a>
            or <a class="btn-cancel" href="#"> {% trans %}Cancel{% endtrans %} </a> 
        </div><p>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div>